function aero = get_aerodynamic_params()
%GET_AERODYNAMIC_PARAMS Restituisce i parametri aerodinamici.

wing = mars_uav.config.get_param('aerodynamic.wing');
polar = mars_uav.config.get_param('aerodynamic.drag_polar');
airfoil = mars_uav.config.get_param('aerodynamic.airfoil');
rotor = mars_uav.config.get_param('aerodynamic.rotorcraft');

aero = struct( ...
    'aspect_ratio', wing.aspect_ratio, ...
    'oswald_e', wing.oswald_efficiency, ...
    'cd0', polar.cd0, ...
    'cl_max', airfoil.cl_max, ...
    'ld_eff_rotorcraft', rotor.ld_effective ...
);
end

