function prop = get_propulsion_efficiencies()
%GET_PROPULSION_EFFICIENCIES Restituisce i parametri di efficienza propulsiva.

rotor = mars_uav.config.get_param('propulsion.rotor');
elec = mars_uav.config.get_param('propulsion.electromechanical');

prop = struct( ...
    'figure_of_merit', rotor.figure_of_merit, ...
    'eta_motor', elec.eta_motor, ...
    'eta_esc', elec.eta_esc, ...
    'eta_prop', elec.eta_prop ...
);
end

