function mission = get_mission_params()
%GET_MISSION_PARAMS Restituisce i parametri di missione.

vel = mars_uav.config.get_param('mission.velocity');
time = mars_uav.config.get_param('mission.time');
energy = mars_uav.config.get_param('mission.energy');
mass_frac = mars_uav.config.get_param('mission.mass_fractions');

mission = struct( ...
    'v_cruise', vel.v_cruise_m_s, ...
    'v_stall', vel.v_stall_m_s, ...
    't_hover_s', time.t_hover_s, ...
    't_cruise_min', time.t_cruise_min, ...
    'energy_reserve', energy.reserve_fraction, ...
    'f_batt', mass_frac.f_battery ...
);
end

