classdef mass_breakdown
    %MASS_BREAKDOWN Calcoli suddivisione masse propulsione.

    methods(Static)
        function breakdown = get_propulsion_mass_breakdown()
            lift_motor_mass = mars_uav.config.get_param('propulsion.components.lift.motor.mass_kg');
            lift_motor_qty = mars_uav.config.get_param('propulsion.components.lift.motor.quantity');
            lift_esc_mass = mars_uav.config.get_param('propulsion.components.lift.esc.mass_kg');
            lift_esc_qty = mars_uav.config.get_param('propulsion.components.lift.esc.quantity');
            lift_prop_mass = mars_uav.config.get_param('propulsion.components.lift.propeller.mass_kg');
            lift_prop_qty = mars_uav.config.get_param('propulsion.components.lift.propeller.quantity');

            cruise_motor_mass = mars_uav.config.get_param('propulsion.components.cruise.motor.mass_kg');
            cruise_motor_qty = mars_uav.config.get_param('propulsion.components.cruise.motor.quantity');
            cruise_esc_mass = mars_uav.config.get_param('propulsion.components.cruise.esc.mass_kg');
            cruise_esc_qty = mars_uav.config.get_param('propulsion.components.cruise.esc.quantity');
            cruise_prop_mass = mars_uav.config.get_param('propulsion.components.cruise.propeller.mass_kg');
            cruise_prop_qty = mars_uav.config.get_param('propulsion.components.cruise.propeller.quantity');

            lift_motors_total = lift_motor_mass * lift_motor_qty;
            lift_escs_total = lift_esc_mass * lift_esc_qty;
            lift_props_total = lift_prop_mass * lift_prop_qty;
            lift_system_total = lift_motors_total + lift_escs_total + lift_props_total;

            cruise_motors_total = cruise_motor_mass * cruise_motor_qty;
            cruise_escs_total = cruise_esc_mass * cruise_esc_qty;
            cruise_props_total = cruise_prop_mass * cruise_prop_qty;
            cruise_system_total = cruise_motors_total + cruise_escs_total + cruise_props_total;

            mounting_total = 0.0;
            wiring_total = 0.0;

            try
                mounting_mass = mars_uav.config.get_param('propulsion.components.shared.mounting.mass_kg');
                mounting_qty = mars_uav.config.get_param('propulsion.components.shared.mounting.quantity');
                mounting_total = mounting_mass * mounting_qty;
            catch
            end

            try
                wiring_mass = mars_uav.config.get_param('propulsion.components.shared.wiring.mass_kg');
                wiring_qty = mars_uav.config.get_param('propulsion.components.shared.wiring.quantity');
                wiring_total = wiring_mass * wiring_qty;
            catch
            end

            shared_total = mounting_total + wiring_total;
            total_propulsion = lift_system_total + cruise_system_total + shared_total;

            breakdown = struct( ...
                'lift', struct( ...
                    'motors', struct( ...
                        'unit_mass_kg', lift_motor_mass, ...
                        'quantity', lift_motor_qty, ...
                        'total_kg', lift_motors_total, ...
                        'model', mars_uav.config.get_param('propulsion.components.lift.motor.model') ...
                    ), ...
                    'escs', struct( ...
                        'unit_mass_kg', lift_esc_mass, ...
                        'quantity', lift_esc_qty, ...
                        'total_kg', lift_escs_total, ...
                        'model', mars_uav.config.get_param('propulsion.components.lift.esc.model') ...
                    ), ...
                    'propellers', struct( ...
                        'unit_mass_kg', lift_prop_mass, ...
                        'quantity', lift_prop_qty, ...
                        'total_kg', lift_props_total, ...
                        'model', mars_uav.config.get_param('propulsion.components.lift.propeller.model') ...
                    ), ...
                    'subtotal_kg', lift_system_total ...
                ), ...
                'cruise', struct( ...
                    'motors', struct( ...
                        'unit_mass_kg', cruise_motor_mass, ...
                        'quantity', cruise_motor_qty, ...
                        'total_kg', cruise_motors_total, ...
                        'model', mars_uav.config.get_param('propulsion.components.cruise.motor.model') ...
                    ), ...
                    'escs', struct( ...
                        'unit_mass_kg', cruise_esc_mass, ...
                        'quantity', cruise_esc_qty, ...
                        'total_kg', cruise_escs_total, ...
                        'model', mars_uav.config.get_param('propulsion.components.cruise.esc.model') ...
                    ), ...
                    'propellers', struct( ...
                        'unit_mass_kg', cruise_prop_mass, ...
                        'quantity', cruise_prop_qty, ...
                        'total_kg', cruise_props_total, ...
                        'model', mars_uav.config.get_param('propulsion.components.cruise.propeller.model') ...
                    ), ...
                    'subtotal_kg', cruise_system_total ...
                ), ...
                'shared', struct( ...
                    'mounting', struct('total_kg', mounting_total), ...
                    'wiring', struct('total_kg', wiring_total), ...
                    'subtotal_kg', shared_total ...
                ), ...
                'total_kg', total_propulsion, ...
                'n_lift_motors', lift_motor_qty, ...
                'n_cruise_motors', cruise_motor_qty, ...
                'n_total_motors', lift_motor_qty + cruise_motor_qty ...
            );
        end

        function parametric = get_parametric_mass_estimate()
            mtow = mars_uav.config.get_param('mission.mass.mtow_kg');
            f_prop = mars_uav.config.get_param('mission.mass_fractions.f_propulsion');

            m_propulsion = f_prop * mtow;
            lift_fraction = 0.70;
            cruise_fraction = 0.30;
            m_lift = lift_fraction * m_propulsion;
            m_cruise = cruise_fraction * m_propulsion;

            parametric = struct( ...
                'mtow_kg', mtow, ...
                'f_propulsion', f_prop, ...
                'm_propulsion_kg', m_propulsion, ...
                'lift_fraction', lift_fraction, ...
                'cruise_fraction', cruise_fraction, ...
                'm_lift_kg', m_lift, ...
                'm_cruise_kg', m_cruise ...
            );
        end

        function print_mass_breakdown()
            breakdown = mars_uav.section7.mass_breakdown.get_propulsion_mass_breakdown();
            parametric = mars_uav.section7.mass_breakdown.get_parametric_mass_estimate();
            fmt = @(value, decimals) mars_uav.core.format_number(value, decimals);

            fprintf('%s\n', repmat('=', 1, 70));
            fprintf('SUDDIVISIONE MASSE PROPULSIONE (Sezione 7)\n');
            fprintf('%s\n', repmat('=', 1, 70));

            fprintf('\nSISTEMA LIFT (Octocottero - 4 coppie coassiali)\n');
            fprintf('%s\n', repmat('-', 1, 50));
            lift = breakdown.lift;
            fprintf('  Motori:     %2s x %s kg = %s kg\n', ...
                fmt(lift.motors.quantity, 0), fmt(lift.motors.unit_mass_kg, 4), fmt(lift.motors.total_kg, 4));
            fprintf('  ESC:        %2s x %s kg = %s kg\n', ...
                fmt(lift.escs.quantity, 0), fmt(lift.escs.unit_mass_kg, 4), fmt(lift.escs.total_kg, 4));
            fprintf('  Eliche:     %2s x %s kg = %s kg\n', ...
                fmt(lift.propellers.quantity, 0), fmt(lift.propellers.unit_mass_kg, 4), fmt(lift.propellers.total_kg, 4));
            fprintf('  Subtotale:  %s kg\n', fmt(lift.subtotal_kg, 4));

            fprintf('\nSISTEMA CROCIERA (Trattore coassiale)\n');
            fprintf('%s\n', repmat('-', 1, 50));
            cruise = breakdown.cruise;
            fprintf('  Motori:     %2s x %s kg = %s kg\n', ...
                fmt(cruise.motors.quantity, 0), fmt(cruise.motors.unit_mass_kg, 4), fmt(cruise.motors.total_kg, 4));
            fprintf('  ESC:        %2s x %s kg = %s kg\n', ...
                fmt(cruise.escs.quantity, 0), fmt(cruise.escs.unit_mass_kg, 4), fmt(cruise.escs.total_kg, 4));
            fprintf('  Eliche:     %2s x %s kg = %s kg\n', ...
                fmt(cruise.propellers.quantity, 0), fmt(cruise.propellers.unit_mass_kg, 4), fmt(cruise.propellers.total_kg, 4));
            fprintf('  Subtotale:  %s kg\n', fmt(cruise.subtotal_kg, 4));

            fprintf('\nCONDIVISI (stime ingegneristiche)\n');
            fprintf('%s\n', repmat('-', 1, 50));
            shared = breakdown.shared;
            fprintf('  Montaggio:  %s kg\n', fmt(shared.mounting.total_kg, 4));
            fprintf('  Cablaggio:  %s kg\n', fmt(shared.wiring.total_kg, 4));
            fprintf('  Subtotale:  %s kg\n', fmt(shared.subtotal_kg, 4));

            fprintf('\nPROPULSIONE TOTALE\n');
            fprintf('%s\n', repmat('-', 1, 50));
            fprintf('  Motori totali: %s (%s lift + %s crociera)\n', ...
                fmt(breakdown.n_total_motors, 0), fmt(breakdown.n_lift_motors, 0), fmt(breakdown.n_cruise_motors, 0));
            fprintf('  Sistema lift:   %s kg\n', fmt(lift.subtotal_kg, 4));
            fprintf('  Sistema crociera: %s kg\n', fmt(cruise.subtotal_kg, 4));
            fprintf('  Condivisi:     %s kg\n', fmt(shared.subtotal_kg, 4));
            fprintf('  Massa totale:  %s kg\n', fmt(breakdown.total_kg, 4));

            fprintf('\nCONFRONTO PARAMETRICO\n');
            fprintf('%s\n', repmat('-', 1, 50));
            fprintf('  MTOW:                %s kg\n', fmt(parametric.mtow_kg, 2));
            fprintf('  f_propulsione:       %s\n', fmt(parametric.f_propulsion, 2));
            fprintf('  Stima parametrica:  %s kg\n', fmt(parametric.m_propulsion_kg, 4));
            fprintf('  Reale (dettaglio):  %s kg\n', fmt(breakdown.total_kg, 4));

            diff = breakdown.total_kg - parametric.m_propulsion_kg;
            diff_pct = 100 * diff / parametric.m_propulsion_kg;
            diff_text = fmt(abs(diff), 4);
            if diff >= 0
                diff_text = ['+' diff_text];
            else
                diff_text = ['-' diff_text];
            end
            diff_pct_text = fmt(abs(diff_pct), 1);
            if diff_pct >= 0
                diff_pct_text = ['+' diff_pct_text];
            else
                diff_pct_text = ['-' diff_pct_text];
            end
            fprintf('  Differenza:         %s kg (%s%%)\n', diff_text, diff_pct_text);

            if diff < 0
                fprintf('\n  [OK] Bilancio massa soddisfatto con margine %s kg\n', fmt(-diff, 3));
            else
                fprintf('\n  [NO] Bilancio massa superato di %s kg\n', fmt(diff, 3));
            end
        end
    end
end

